### ISSUE TITLE
Unpickler(file).load() issue undefined symbol: cblas_drot

### ISSUE THREAD

**Issue by NagrajN** [thenovices/heroku-buildpack-scipy#25]
Flask
Atlas
numpy==1.9.2
scipy==0.15.1
scikit-learn==0.17
# 

ERR Traceback (most recent call last):
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "hello.py", line 244, in <module>
2015-11-08T18:56:33.42-0800 [App/0]      ERR     clf_hydrated = pickle.loads(svm_rbf_triple)
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/pickle.py", line 1382, in loads
2015-11-08T18:56:33.42-0800 [App/0]      ERR     return Unpickler(file).load()
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/pickle.py", line 858, in load
2015-11-08T18:56:33.42-0800 [App/0]      ERR     dispatch[key](self)
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/pickle.py", line 1090, in load_global
2015-11-08T18:56:33.42-0800 [App/0]      ERR     klass = self.find_class(module, name)
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/pickle.py", line 1124, in find_class
2015-11-08T18:56:33.42-0800 [App/0]      ERR     **import**(module)
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/sklearn/linear_model/**init**.py", line 15, in <module>
2015-11-08T18:56:33.42-0800 [App/0]      ERR     from .least_angle import (Lars, LassoLars, lars_path, LarsCV, LassoLarsCV,
2015-11-08T18:56:33.42-0800 [App/0]      ERR   File "/app/.heroku/python/lib/python2.7/site-packages/sklearn/linear_model/least_angle.py", line 24, in <module>
2015-11-08T18:56:33.42-0800 [App/0]      ERR     from ..utils import arrayfuncs, as_float_array, check_X_y
2015-11-08T18:56:33.42-0800 [App/0]      ERR ImportError: /app/.heroku/python/lib/python2.7/site-packages/sklearn/utils/arrayfuncs.so: undefined symbol: cblas_drot
2015-11-08T18:56:33.44-0800 [App/0]      OUT 
2015-11-08T18:56:33.46-0800 [DEA/26]     ERR Instance (index 0) failed to start accepting connections

**Comment by FreshDonut** [comment]
Same issue. Any updates? I'm importing my pkl file from S3.

```
pillow == 3.2.0
flask == 0.10.1
mock == 1.3.0
gevent == 1.1.0
gunicorn == 19.4.5
numpy == 1.9.2
scipy == 0.15.1
pandas == 0.16.1
scikit-learn == 0.16.1
boto == 2.39.0
```
